api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
        html: ['text/html']
        xml:  ['application/xml' , 'text/xml']    
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
